### ISSUE TITLE
chi2_9* question

### ISSUE THREAD

**Issue by tigrazone** [bacTlink/mitsuba-CPPM#2]
Hello!
Why chi2_95 used but chi2_90, chi2_99 not?
How to use 2 other consts?
What for this consts?

**Comment by zehui-l** [comment]
Please refer to the Tab. 4 in the [paper](https://bactlink.github.io/CPPM/SIGA2020_CPPM_paper.pdf).

The chi2_95 corresponds to significance level 𝛼𝜒 = 0.05.
And the chi2_90, chi2_99 corresponds to 𝛼𝜒 = 0.10 and 𝛼𝜒 = 0.01, respectively.
In our experiments,  𝛼𝜒 = 0.05 has the best performance.

**Comment by bacTlink** [comment]
Please refer to the Tab. 4 in the [paper](https://bactlink.github.io/CPPM/SIGA2020_CPPM_paper.pdf).

The chi2_95 corresponds to significance level 𝛼𝜒 = 0.05.
And the chi2_90, chi2_99 corresponds to 𝛼𝜒 = 0.10 and 𝛼𝜒 = 0.01, respectively.
In our experiments,  𝛼𝜒 = 0.05 has the best performance.

**Comment by tigrazone** [comment]
"best performance" is speed or image quality?

**Comment by bacTlink** [comment]
> "best performance" is speed or image quality?

Minimum MSE after a certain number of iterations.

**Comment by tigrazone** [comment]
Thank you!
